Before update from Bluehost. Bluehost says core files are modified.

diff --git a/wp-content/plugins/tiny-compress-images/bin/test-wordpress b/wp-content/plugins/tiny-compress-images/bin/test-wordpress
--- a/wp-content/plugins/tiny-compress-images/bin/test-wordpress
+++ b/wp-content/plugins/tiny-compress-images/bin/test-wordpress
@@ -28,11 +28,30 @@ export WORDPRESS_DATABASE=wordpress_$version
 export MYSQL_ROOT_PASSWORD=root
 
 if hash docker-machine 2>/dev/null; then
-  export HOST_IP=$(docker-machine ip default)
+  export HOST_IP=$(docker-machine ip $DOCKER_MACHINE_NAME)
 else
   export HOST_IP=$(boot2docker ip)
+fi
+if [ -z "$HOST_IP" ]; then
+  echo "Could not find docker machine ip"
+  exit 2
 fi
 
 export HOST_PORT=80$version
 export WORDPRESS_URL=http://$HOST_IP:$HOST_PORT
+
+function prepare_test_config {
+  printf "\nPreparing test config\n\n"
+  mv src/config/tiny-config.php src/config/tiny-config.php.bak
+  cp test/fixtures/tiny-config.php src/config/tiny-config.php
+}
+
+function restore_config {
+  printf "\n\nRestoring config\n\n"
+  mv src/config/tiny-config.php.bak src/config/tiny-config.php
+}
+
+trap 'restore_config' EXIT
+
+prepare_test_config
 vendor/bin/phpunit "$PHPUNIT_ARG"
